name: React CI/CD

on:
  push:
    branches:
      - deploy

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]  # You can choose the Node.js version you need

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm i --verbose  # Use verbose mode for debugging

    - name: Authenticate with Private Registry
      run: |
        npm login --registry=https://your-private-registry.com --scope=@your-scope --always-auth
        npm config set //your-private-registry.com/:_authToken=${NODE_AUTH_TOKEN}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Set NPM Registry to Public
      run: npm config set registry https://registry.npmjs.org/

    - name: Clear NPM Cache
      run: npm cache clean --force

    - name: Run Tests
      run: npm test

    - name: Build
      run: npm run build
